<?php
require_once('guiconfig.inc');require_once('/usr/local/pkg/suricata/suricata.inc');
$pgtitle=[gettext('Services'),gettext('Suricata'),gettext('Events')];$pglinks=['','/suricata/suricata_overview.php','@self'];
$type=$_GET['type']??'alert';$allowed=['all','alert','drop','flow','dns','http','tls','fileinfo','anomaly'];if(!in_array($type,$allowed,true))$type='alert';
$interface=$_GET['interface']??'all';$events=[];$interfaces=config_get_path('installedpackages/suricata/rule',[]);
foreach($interfaces as $entry){if($interface!=='all'&&(string)$entry['uuid']!==$interface)continue;$real=get_real_interface($entry['interface']??'');$path=SURICATALOGDIR."suricata_{$real}{$entry['uuid']}/eve.json";if(!is_file($path))continue;$lines=[];exec('/usr/bin/tail -n 750 '.escapeshellarg($path),$lines,$rc);foreach($lines as $line){$event=json_decode($line,true);if(!is_array($event))continue;if($type!=='all'&&($event['event_type']??'')!==$type)continue;$event['_interface']=$entry['descr']??$real;$events[]=$event;}}
usort($events,fn($a,$b)=>strcmp($b['timestamp']??'',$a['timestamp']??''));$events=array_slice($events,0,500);
include('head.inc');suricata_display_primary_navigation('events');
?>
<div class="card mb-3"><div class="card-body"><form method="get" class="row g-2"><div class="col-md-3"><label class="form-label" for="type"><?=gettext('Event type')?></label><select class="form-select" id="type" name="type"><?php foreach($allowed as $value):?><option value="<?=$value?>" <?=$type===$value?'selected':''?>><?=htmlspecialchars(ucfirst($value))?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label" for="interface"><?=gettext('Interface')?></label><select class="form-select" id="interface" name="interface"><option value="all"><?=gettext('All interfaces')?></option><?php foreach($interfaces as $entry):?><option value="<?=htmlspecialchars($entry['uuid'])?>" <?=$interface===(string)$entry['uuid']?'selected':''?>><?=htmlspecialchars($entry['descr']??$entry['interface'])?></option><?php endforeach;?></select></div><div class="col align-self-end"><button class="btn btn-primary"><?=gettext('Apply filter')?></button></div></form></div></div>
<div class="card"><div class="card-header d-flex justify-content-between"><h2 class="h5 mb-0"><?=gettext('Recent EVE events')?></h2><span class="badge text-bg-secondary"><?=count($events)?> / 500</span></div><div class="card-body table-responsive"><table class="table table-sm table-hover"><thead><tr><th><?=gettext('Time')?></th><th><?=gettext('Interface')?></th><th><?=gettext('Type')?></th><th><?=gettext('Source')?></th><th><?=gettext('Destination')?></th><th><?=gettext('Details')?></th></tr></thead><tbody><?php foreach($events as $event):$alert=$event['alert']??[];?><tr><td class="text-nowrap"><?=htmlspecialchars($event['timestamp']??'')?></td><td><?=htmlspecialchars($event['_interface'])?></td><td><span class="badge text-bg-secondary"><?=htmlspecialchars($event['event_type']??'')?></span></td><td><code><?=htmlspecialchars(($event['src_ip']??'').(isset($event['src_port'])?':'.$event['src_port']:''))?></code></td><td><code><?=htmlspecialchars(($event['dest_ip']??'').(isset($event['dest_port'])?':'.$event['dest_port']:''))?></code></td><td><?=htmlspecialchars($alert['signature']??$event['app_proto']??$event['proto']??'')?></td></tr><?php endforeach;?></tbody></table><?php if(!$events):?><div class="text-center text-body-secondary py-4"><?=gettext('No matching events were found in the bounded recent log window.')?></div><?php endif;?></div></div>
<?php include('foot.inc');?>
