<?php
/* FreeSense Web Gateway 2.0: ICAP and malware scanning. */
require_once('guiconfig.inc'); require_once('webgateway.inc');
$wg_config=webgateway_config();$pconfig=$wg_config;$input_errors=[];$savemsg=null;
if($_POST){$pconfig=array_merge($wg_config,$_POST);foreach(['icap_enable','local_av_enable'] as $f)$pconfig[$f]=isset($_POST[$f])?'on':'';if(webgateway_save_candidate($pconfig,gettext('Web Gateway threat protection changed'),$input_errors)){$savemsg=gettext('Threat protection saved and applied.');$wg_config=$pconfig=webgateway_config();}}
$local_available=is_executable('/usr/local/bin/c-icap')&&is_executable('/usr/local/sbin/clamd')&&is_file('/usr/local/lib/c_icap/squidclamav.so');
$pgtitle=[gettext('Services'),gettext('Web Gateway'),gettext('Threat Protection')];include('head.inc');webgateway_display_tabs('threat');if($input_errors)print_input_errors($input_errors);if($savemsg)print_info_box($savemsg,'success');
?>
<form method="post">
<div class="row g-3 mb-3"><div class="col-lg-6"><div class="card h-100"><div class="card-header"><h2 class="h5 mb-0"><i class="fa-solid fa-plug me-2"></i><?=gettext('External ICAP')?></h2></div><div class="card-body"><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" id="icap_enable" name="icap_enable" <?=$pconfig['icap_enable']==='on'?'checked':''?>><label class="form-check-label fw-semibold" for="icap_enable"><?=gettext('Enable external ICAP adaptation')?></label></div><label class="form-label"><?=gettext('REQMOD service URL')?></label><input class="form-control mb-3" name="icap_req_url" placeholder="icaps://scanner.example:1344/request" value="<?=htmlspecialchars($pconfig['icap_req_url'])?>"><label class="form-label"><?=gettext('RESPMOD service URL')?></label><input class="form-control mb-3" name="icap_resp_url" placeholder="icaps://scanner.example:1344/response" value="<?=htmlspecialchars($pconfig['icap_resp_url'])?>"><label class="form-label"><?=gettext('If the ICAP service fails')?></label><select class="form-select" name="icap_failure"><option value="bypass" <?=$pconfig['icap_failure']==='bypass'?'selected':''?>><?=gettext('Bypass and alert')?></option><option value="closed" <?=$pconfig['icap_failure']==='closed'?'selected':''?>><?=gettext('Block eligible traffic')?></option></select></div></div></div>
<div class="col-lg-6"><div class="card h-100 <?=$local_available?'border-success':'border-secondary'?>"><div class="card-header"><h2 class="h5 mb-0"><i class="fa-solid fa-shield-virus me-2"></i><?=gettext('Local malware scanner')?></h2></div><div class="card-body"><div class="d-flex justify-content-between mb-3"><span class="badge bg-<?=$local_available?'success':'secondary'?>"><?=$local_available?gettext('AV companion installed'):gettext('AV companion not installed')?></span></div><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" id="local_av_enable" name="local_av_enable" <?=$pconfig['local_av_enable']==='on'?'checked':''?> <?=$local_available?'':'disabled'?>> <label class="form-check-label fw-semibold" for="local_av_enable"><?=gettext('Scan requests and responses with ClamAV/c-icap')?></label></div><div class="row g-3"><div class="col-md-6"><label class="form-label"><?=gettext('Maximum scanned object (MiB)')?></label><input class="form-control" type="number" min="1" max="4096" name="av_max_mb" value="<?=htmlspecialchars($pconfig['av_max_mb'])?>"></div><div class="col-md-6"><label class="form-label"><?=gettext('Scanner failure')?></label><select class="form-select" name="av_failure"><option value="closed" <?=$pconfig['av_failure']==='closed'?'selected':''?>><?=gettext('Block (recommended)')?></option><option value="bypass" <?=$pconfig['av_failure']==='bypass'?'selected':''?>><?=gettext('Bypass and alert')?></option></select></div></div><p class="form-text mt-3"><?=gettext('HTTPS response bodies are available to scanners only for inspected destinations. Archive and decompression limits are enforced by the AV companion configuration.')?></p></div></div></div></div>
<div class="alert alert-info"><i class="fa-solid fa-flask me-2"></i><?=gettext('Diagnostics provides ICAP connectivity and EICAR tests without storing the test object in the cache.')?></div>
<button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk icon-embed-btn"></i><?=gettext('Save threat protection')?></button>
</form>
<?php include('foot.inc');?>
