<?php
/* FreeSense Web Gateway 2.0: native threat/category feeds. */
require_once('guiconfig.inc');require_once('webgateway.inc');
$wg_config=webgateway_config();$pconfig=$wg_config;$input_errors=[];$savemsg=null;
if($_POST&&isset($_POST['update_now'])){if(webgateway_update_feeds($message))$savemsg=$message;else $input_errors[]=$message;}
elseif($_POST){$pconfig=array_merge($wg_config,$_POST);$pconfig['feeds_enable']=isset($_POST['feeds_enable'])?'on':'';$pconfig['feed_urls']=webgateway_encode_list($_POST['feed_urls_text']??'');if(webgateway_save_candidate($pconfig,gettext('Web Gateway feed settings changed'),$input_errors)){$savemsg=gettext('Feed settings saved. Use Update now to compile the first database.');$wg_config=$pconfig=webgateway_config();}}
$status=[];if(is_readable(WEBGATEWAY_STATE_DIR.'/feeds/status.json'))$status=json_decode(file_get_contents(WEBGATEWAY_STATE_DIR.'/feeds/status.json'),true)?:[];
$pgtitle=[gettext('Services'),gettext('Web Gateway'),gettext('Feeds')];include('head.inc');webgateway_display_tabs('feeds');if($input_errors)print_input_errors($input_errors);if($savemsg)print_info_box($savemsg,'success');
?>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted text-uppercase small"><?=gettext('Compiled entries')?></div><div class="fs-3"><?=number_format($status['entries']??0)?></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted text-uppercase small"><?=gettext('Sources')?></div><div class="fs-3"><?=number_format($status['sources']??0)?></div></div></div></div><div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted text-uppercase small"><?=gettext('Last successful update')?></div><div class="fs-5"><?=isset($status['updated'])?htmlspecialchars(date('Y-m-d H:i:s',$status['updated'])):gettext('Never')?></div></div></div></div></div>
<form method="post"><div class="card mb-3"><div class="card-header"><h2 class="h5 mb-0"><i class="fa-solid fa-cloud-arrow-down me-2"></i><?=gettext('Policy feeds')?></h2></div><div class="card-body"><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" id="feeds_enable" name="feeds_enable" <?=$pconfig['feeds_enable']==='on'?'checked':''?>><label class="form-check-label fw-semibold" for="feeds_enable"><?=gettext('Enable scheduled feed updates')?></label></div><label class="form-label"><?=gettext('HTTPS feed URLs')?></label><textarea class="form-control font-monospace" name="feed_urls_text" rows="9" placeholder="https://provider.example/domains.txt"><?=htmlspecialchars(webgateway_decode_list($pconfig['feed_urls']))?></textarea><div class="form-text"><?=gettext('Plain domain or hosts-format feeds are normalized and deduplicated. Downloads are staged and the last-known-good database stays active after any failure.')?></div><div class="row g-3 mt-1"><div class="col-md-3"><label class="form-label"><?=gettext('Interval (hours)')?></label><input class="form-control" type="number" min="1" max="720" name="feed_interval" value="<?=htmlspecialchars($pconfig['feed_interval'])?>"></div><div class="col-md-3"><label class="form-label"><?=gettext('Maximum download (MiB)')?></label><input class="form-control" type="number" min="1" max="1024" name="feed_max_mb" value="<?=htmlspecialchars($pconfig['feed_max_mb'])?>"></div><div class="col-md-3"><label class="form-label"><?=gettext('Maximum entries')?></label><input class="form-control" type="number" min="1" max="5000000" name="feed_max_entries" value="<?=htmlspecialchars($pconfig['feed_max_entries'])?>"></div></div></div></div><div class="d-flex gap-2"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk icon-embed-btn"></i><?=gettext('Save feed settings')?></button><button class="btn btn-outline-info" type="submit" name="update_now" value="1"><i class="fa-solid fa-arrows-rotate icon-embed-btn"></i><?=gettext('Update now')?></button></div></form>
<div class="alert alert-warning mt-3"><i class="fa-solid fa-scale-balanced me-2"></i><?=gettext('FreeSense does not silently bundle third-party blocklists. Review each provider’s licensing, privacy terms and false-positive process before adding it.')?></div>
<?php include('foot.inc');?>
