# $FreeBSD$

MASTERDIR=	${.CURDIR}/../FreeSense-pkg-zabbix-proxy

PORTNAME=	FreeSense-pkg-zabbix-proxy7

CONFLICTS=	FreeSense-pkg-zabbix-proxy

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix7-proxy

ZABBIXINTERNALNAME=	zabbix-proxy7
ZABBIXTITLE=	Zabbix Proxy 7
ZABBIXVERSION=	7

PORTREVISION=	2

.include "${MASTERDIR}/Makefile"
