# $FreeBSD

MASTERDIR=	${.CURDIR}/../FreeSense-pkg-zabbix-agent

PORTNAME=	FreeSense-pkg-zabbix-agent7

CONFLICTS=	FreeSense-pkg-zabbix-agent

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix7-agent

ZABBIXINTERNALNAME=	zabbix-agent7
ZABBIXTITLE=	Zabbix Agent 7
ZABBIXVERSION=	7

PORTREVISION=	2

.include "${MASTERDIR}/Makefile"
